adding hcc-devprod
redhat-appstudio/tenants-config pull request #210
Opened 2024-02-08 17:54 UTC by maknop

2024-02-08 18:24 UTC, maknop commented
@scoheb @gbenhaim @ernesgonzalez33  Can I get a review please? :)

2024-02-08 19:44 UTC, ernesgonzalez33 requested changes

2024-02-08 19:44 UTC, ernesgonzalez33 commented on cluster/stone-prd-rh01/tenants/hcc-devprod-tenant/kustomization.yaml
> +  - ../../../../lib/consoledot-test-pipeline
This line is for the Clowder integration. Do the `ephemeral-namespace-operator` needs to be tested using itself? And if that's the case, you are still missing the `IntegrationTestScenario` that points to the Tekton pipeline with the integration

2024-02-09 09:33 UTC, ernesgonzalez33 approved these changes

2024-02-09 09:33 UTC, merged